CI: update `build.yml`
- Update `action/checkout` from `v2` to `v4`
- Add `action/upload-artifact`

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,9 @@
 name: Build LaTeX TikZ Project
 
-on: [push]
+on:
+  push:
+    branches:
+      - main
 
 jobs:
   build:
@@ -8,18 +11,25 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up LaTeX
         run: |
           sudo apt-get update
           sudo apt-get install -y --no-install-recommends texlive-base texlive-latex-extra
 
-      - name: Build all LaTeX projects
+      - name: Build LaTeX projects
         run: |
-          find . -name "main.tex" -execdir sh -c 'pdflatex -interaction=nonstopmode -halt-on-error {} && echo "Build completed successfully."' || echo "Build failed." \;
+          find . -type f -name "main.tex" -exec sh -c 'pdflatex -interaction=nonstopmode -halt-on-error "$1" && echo "Build completed successfully."' _ {} \; || echo "Build failed."
 
       - name: Archive all PDFs
         run: |
-          find . -name "main.pdf" -execdir cp {} {}.pdf \;
-          find . -name "main.pdf.pdf" -execdir uses: actions/upload-artifact@v2  with: { name: {}  path: {} } \;
+          find . -type f -name "main.pdf" -exec sh -c 'cp "$1" "${1%.pdf}_copy.pdf"' _ {} \;
+          find . -type f -name "*_copy.pdf" -exec sh -c 'echo "::set-output name=pdf_path::$(realpath $1)"' _ {} \;
+        id: archive
+
+      - name: Upload PDF artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: PDFs
+          path: ${{ steps.archive.outputs.pdf_path }}
